### ISSUE TITLE
TODO: Preliminarily migrate modules from trove

### ISSUE THREAD

**Issue by hyunjongkimmath** [hyunjongkimmath/trouver#11]
I was writing a package called `trove` with the old version of nbdev, but now that the new version is available and better (for example, I can use `nbdev_preview` to see what a website rendering would look like without making the GitHub repository public or without using Ubuntu), I need to migrate my code to `trouver`. I decided to not rely on nbdev's migration because I need to change the docstring formatting of the methods/functions in `trove` to better fit that recommended by nbdev.

The objective in this preliminary migration is not to migrate the files and make nearly perfect edits, but rather to 
1. reformat the docstrings
2. rearrange any existing examples/tests to better suit nbdev's recommendations/abilities
3. modify existing examples/tests so that the tests not only pass in the notebooks, but also pass on GitHub actions.

- [x] Migrate `helper`
- [x] Migrate `latex.__init__`
- [x] Migrate `latex.convert`
- [ ] Migrate `machine_learning.__init__`
- [ ] Migrate `machine_learning.train`
- [ ] Migrate `markdown.markdown.__init__`
- [x] Migrate `markdown.markdown.file`
- [x] Migrate `markdown.markdown.heading`
- [x] Migrate `markdown.obsidian.__init__`
- [x] Migrate `markdown.obsidian.footnotes`
- [x] Migrate `markdown.obsidian.links`
- [x] Migrate `markdown.obsidian.personal.__init__`
- [x] MIgrate `markdown.obsidian.personal.authors`
- [ ] Migrate `markdown.obsidian.personal.cleanup`
- [ ] Migrate `markdown.obsidian.personal.definition`
- [ ] Migrate `markdown.obsidian.personal.glossary`
- [x] Migrate `markdown.obsidian.personal.index_notes`
- [ ] Migrate `markdown.obsidian.personal.information_notes`
- [ ] Migrate `markdown.obsidian.personal.machine_learning.definition.ipynb`
- [ ] Migrate `markdown.obsidian.personal.notation`
- [ ] Migrate `markdown.obsidian.personal.note_processing`
- [x] Migrate `markdown.obsidian.personal.note_type`
- [x] Migrate `markdown.obsidian.personal.notes`
- [x] Migrate `markdown.obsidian.personal.reference`
- [ ] Migrate `markdown.obsidian.personal.terms`
- [x] Migrate `markdown.obsidian.tags`
- [x] Migrate `markdown.obsidian.vault`
