### ISSUE TITLE
TODO: Add examples and/or docstrings for methods/functions

### ISSUE THREAD

**Issue by hyunjongkimmath** [hyunjongkimmath/trouver#7]
- [ ] Add examples for the `all_custom_text_for_links_in_vault` and `all_links_in_vault` functions in `06_markdown.obsidian.links.ipynb`.
- [ ] Add examples and docstrings for every function/method in `07_markdown.obsidian.tags`.
- [ ] Add tests for `merge_in_line_latex`, `copy` methods in `MarkdownFile` class in `04_markdown.markdown.file.ipynb`.
- [ ] `04_markdown.markdown.file.ipynb` has a lot of missing examples.
- [ ] Add examples for `11_markdown.obsidian.personal.authors.ipynb
- [ ] In `04_markdown.markdown.file.ipynb`, some of the examples are hard to read because they use, for example, `template_mf` which is constructed in other examples. Change it so that `template_mf` is constructed at each example thereby making the examples self-contained..
